1. Memuat Data

In [186]:
import pandas as pd

In [187]:
#membaca file CSV (Comma Separated Values) dan mengubahnya menjadi DataFrame Pandas
df = pd.read_csv('/content/sample_data/movie_sample_dataset.csv')

2. Memeriksa Data

In [188]:
# menampilkan beberapa baris pertama dari dataset untuk mengecek struktur data
# default = 5 baris
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

In [189]:
# mengetahui ukuran dataset
# hasil (99, 13) artinya jumlah baris = 99 dan jumlah kolom = 13
df.shape

(99, 13)

3. Membersihkan Data

In [190]:
import numpy as np

# replace "?" menjadi NaN
df.replace("?", np.nan, inplace = True)

# cek banyaknya missing value pada masing-masing kolom
print(df.isnull().sum())

# color = 11 missing value
# director name = 11 missing value
# genres = 1 missing value
# budget = 4 missing value

color                   11
director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

In [191]:
# menghapus baris yang memiliki nilai NaN di kolom gross

# simply drop whole row with NaN in "gross" column
df.dropna(subset=["gross"], axis=0, inplace=True)
# reset index, because we droped two rows
df.reset_index(drop=True, inplace=True)
print(df.head())

    color      director_name  duration        gross  \
0   Color    Martin Scorsese       240  116866727.0
1   Color        Shane Black       195  408992272.0
2  color   Quentin Tarantino       187   54116191.0
3   Color   Kenneth Lonergan       186      46495.0
4   Color      Peter Jackson       186  258355354.0

                                 genres                          movie_title  \
0          Biography|Comedy|Crime|Drama              The Wolf of Wall Street
1               Action|Adventure|Sci-Fi                           Iron Man 3
2  Crime|Drama|Mystery|Thriller|Western                    The Hateful Eight
3                                 Drama                             Margaret
4                     Adventure|Fantasy  The Hobbit: The Desolation of Smaug

   title_year language country       budget  imdb_score  \
0        2013  English     USA  100000000.0         8.2
1        2013  English     USA  200000000.0         7.2
2        2015  English     USA   44000000.0         7.9
3        2011  English     usa   14000000.0         6.5
4        2013  English     USA  225000000.0         7.9

                                              actors  movie_facebook_likes
0  Leonardo DiCaprio,Matthew McConaughey,Jon Favreau                138000
1          Robert Downey Jr.,Jon Favreau,Don Cheadle                 95000
2          Craig Stark,Jennifer Jason Leigh,Zoë Bell                114000
3        Matt Damon,Kieran Culkin,John Gallagher Jr.                     0
4              Aidan Turner,Adam Brown,James Nesbitt                 83000

In [192]:
# menghapus baris yang memiliki nilai NaN di kolom budget

# simply drop whole row with NaN in "budget" column
df.dropna(subset=["budget"], axis=0, inplace=True)
# reset index, because we droped two rows
df.reset_index(drop=True, inplace=True)
print(df.head())

    color      director_name  duration        gross  \
0   Color    Martin Scorsese       240  116866727.0
1   Color        Shane Black       195  408992272.0
2  color   Quentin Tarantino       187   54116191.0
3   Color   Kenneth Lonergan       186      46495.0
4   Color      Peter Jackson       186  258355354.0

                                 genres                          movie_title  \
0          Biography|Comedy|Crime|Drama              The Wolf of Wall Street
1               Action|Adventure|Sci-Fi                           Iron Man 3
2  Crime|Drama|Mystery|Thriller|Western                    The Hateful Eight
3                                 Drama                             Margaret
4                     Adventure|Fantasy  The Hobbit: The Desolation of Smaug

   title_year language country       budget  imdb_score  \
0        2013  English     USA  100000000.0         8.2
1        2013  English     USA  200000000.0         7.2
2        2015  English     USA   44000000.0         7.9
3        2011  English     usa   14000000.0         6.5
4        2013  English     USA  225000000.0         7.9

                                              actors  movie_facebook_likes
0  Leonardo DiCaprio,Matthew McConaughey,Jon Favreau                138000
1          Robert Downey Jr.,Jon Favreau,Don Cheadle                 95000
2          Craig Stark,Jennifer Jason Leigh,Zoë Bell                114000
3        Matt Damon,Kieran Culkin,John Gallagher Jr.                     0
4              Aidan Turner,Adam Brown,James Nesbitt                 83000

In [193]:
# cek ulang banyaknya missing value pada masing-masing kolom
print(df.isnull().sum())

color                   10
director_name           10
duration                 0
gross                    0
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   0
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

In [194]:
# jumlah cek baris dan kolom setelah missing value dihilangkan
df.shape

(89, 13)

In [195]:
# mengatasi nilai yg tdk konsisten atau kesalahan penulisan di kolom.
# mengganti kata 'Color' mjd 'color'.

df['color'] = df['color'].str.strip().str.lower()
print(df["color"].value_counts())

color
color              78
black and white     1
Name: count, dtype: int64

In [196]:
#menghapus nilai-nilai tidak standar, seperti N/A
df = df.dropna()
print(df.isnull().sum())

color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

4. Transformasi Data

In [197]:
#mengubah tipe data kolom menjadi tipe data yg sesuai
df.dtypes

color                    object
director_name            object
duration                  int64
gross                   float64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                  float64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [198]:
#pisahkan genre yg bergabung dlm 1 kolom mjd bbrp kolom terpisah

# buat dummy variable untuk semua genre
df_genres_ohe = df['genres'].str.get_dummies(sep='|')

# gabungkan ke dataframe asli
df_ohe = pd.concat([df, df_genres_ohe], axis=1)

print(df_ohe.head(10))

    color      director_name  duration        gross  \
0   color    Martin Scorsese       240  116866727.0
1   color        Shane Black       195  408992272.0
2   color  Quentin Tarantino       187   54116191.0
3   color   Kenneth Lonergan       186      46495.0
4   color      Peter Jackson       186  258355354.0
6   color      Peter Jackson       -50  303001229.0
7   color        Joss Whedon       173  623279547.0
8   color        Joss Whedon       173  623279547.0
10  color               Null       158  102515793.0
12  color  Christopher Nolan       169  187991439.0

                                  genres                          movie_title  \
0           Biography|Comedy|Crime|Drama              The Wolf of Wall Street
1                Action|Adventure|Sci-Fi                           Iron Man 3
2   Crime|Drama|Mystery|Thriller|Western                    The Hateful Eight
3                                  Drama                             Margaret
4                      Adventure|Fantasy  The Hobbit: The Desolation of Smaug
6                      Adventure|Fantasy    The Hobbit: An Unexpected Journey
7                Action|Adventure|Sci-Fi                         The Avengers
8                Action|Adventure|Sci-Fi                         The Avengers
10          Crime|Drama|Mystery|Thriller      The Girl with the Dragon Tattoo
12                Adventure|Drama|Sci-Fi                         Interstellar

    title_year language country       budget  ...  History Music  Musical  \
0         2013  English     USA  100000000.0  ...        0     0        0
1         2013  English     USA  200000000.0  ...        0     0        0
2         2015  English     USA   44000000.0  ...        0     0        0
3         2011  English     usa   14000000.0  ...        0     0        0
4         2013  English     USA  225000000.0  ...        0     0        0
6         2012  English     USA  180000000.0  ...        0     0        0
7         2012  English     USA  220000000.0  ...        0     0        0
8         2012  English     USA  220000000.0  ...        0     0        0
10        2011  English     USA   90000000.0  ...        0     0        0
12        2014  English     USA  165000000.0  ...        0     0        0

    Mystery  Romance  Sci-Fi  Sport  Thriller  War  Western
0         0        0       0      0         0    0        0
1         0        0       1      0         0    0        0
2         1        0       0      0         1    0        1
3         0        0       0      0         0    0        0
4         0        0       0      0         0    0        0
6         0        0       0      0         0    0        0
7         0        0       1      0         0    0        0
8         0        0       1      0         0    0        0
10        1        0       0      0         1    0        0
12        0        0       1      0         0    0        0

[10 rows x 30 columns]

In [199]:
# cek banyaknya missing value pada masing-masing kolom
print(df.isnull().sum())

color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

In [200]:
#normalisasi teks untuk memastikan konsistensi
for col in df_ohe.select_dtypes(include='object').columns:
    df_ohe[col] = df_ohe[col].str.strip().str.lower()
    df_ohe.columns = df_ohe.columns.str.strip().str.lower()

print(df_ohe.head(10))

    color      director_name  duration        gross  \
0   color    martin scorsese       240  116866727.0
1   color        shane black       195  408992272.0
2   color  quentin tarantino       187   54116191.0
3   color   kenneth lonergan       186      46495.0
4   color      peter jackson       186  258355354.0
6   color      peter jackson       -50  303001229.0
7   color        joss whedon       173  623279547.0
8   color        joss whedon       173  623279547.0
10  color               null       158  102515793.0
12  color  christopher nolan       169  187991439.0

                                  genres                          movie_title  \
0           biography|comedy|crime|drama              the wolf of wall street
1                action|adventure|sci-fi                           iron man 3
2   crime|drama|mystery|thriller|western                    the hateful eight
3                                  drama                             margaret
4                      adventure|fantasy  the hobbit: the desolation of smaug
6                      adventure|fantasy    the hobbit: an unexpected journey
7                action|adventure|sci-fi                         the avengers
8                action|adventure|sci-fi                         the avengers
10          crime|drama|mystery|thriller      the girl with the dragon tattoo
12                adventure|drama|sci-fi                         interstellar

    title_year language country       budget  ...  history music  musical  \
0         2013  english     usa  100000000.0  ...        0     0        0
1         2013  english     usa  200000000.0  ...        0     0        0
2         2015  english     usa   44000000.0  ...        0     0        0
3         2011  english     usa   14000000.0  ...        0     0        0
4         2013  english     usa  225000000.0  ...        0     0        0
6         2012  english     usa  180000000.0  ...        0     0        0
7         2012  english     usa  220000000.0  ...        0     0        0
8         2012  english     usa  220000000.0  ...        0     0        0
10        2011  english     usa   90000000.0  ...        0     0        0
12        2014  english     usa  165000000.0  ...        0     0        0

    mystery  romance  sci-fi  sport  thriller  war  western
0         0        0       0      0         0    0        0
1         0        0       1      0         0    0        0
2         1        0       0      0         1    0        1
3         0        0       0      0         0    0        0
4         0        0       0      0         0    0        0
6         0        0       0      0         0    0        0
7         0        0       1      0         0    0        0
8         0        0       1      0         0    0        0
10        1        0       0      0         1    0        0
12        0        0       1      0         0    0        0

[10 rows x 30 columns]

In [201]:
#simpan data yg telah dilakukan preprocessing ke dalam file CSV baru
df_ohe.to_csv('movie_dataset_cleaned.csv')